
module.exports = `
<!--
File: index.html
Author: Vezetéknév Keresztnév
Copyright: 2024, Vezetéknév Keresztnév
Group: Csoportnév
Date: 2024-12-02
Github: https://github.com/valami12345/
Licenc: MIT
-->

<!DOCTYPE html>
<html lang="hu">
  <head>
    <meta charset="UTF-8">
    <title>Sinto esbuild</title>
    <link rel="stylesheet" href="bootstrap.css">
    <link rel="stylesheet" href="style.css">    
  </head>
  <body>
    <div class="container">
        <h1>Sinto</h1>
        <p>The website generated by Sinto.</p>      

    </div>
    <script src="bootstrap.js"></script>
    <script src="app.js"></script>
  </body>
</html>
`
