
module.exports = `
<!DOCTYPE html>
<html lang="hu">
  <head>
    <meta charset="UTF-8">
    <title>Sinto webpack</title>
  </head>
  <body>
    <div class="container">
        <h1>Sinto</h1>
        <p>The website generated by Sinto.</p>      

    </div>
    <script src="main.js"></script>
  </body>
</html>
`
